version: '3.8'
services:
  web:
    image: v1ceo/yamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - base_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    depends_on:
      - web
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./data/certbot/conf:/etc/letsencrypt

      - ./data/certbot/www:/var/www/certbot

      - static_value:/var/html/static/

      - media_value:/var/html/media/
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
volumes:
  static_value:
  media_value:
  base_value: